/****** Object:  Table [dbo].[ProcessSteps]    Script Date: 9/19/2015 8:55:23 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ProcessSteps](
	[StepId] [bigint] NOT NULL,
	[Name] [varchar](30) NULL,
	[Version] [varchar](3) NULL,
 CONSTRAINT [PK_ProcessSteps] PRIMARY KEY CLUSTERED 
(
	[StepId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

