//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contoso.Azure.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contoso_SalesOrders
    {
        public string EntityId { get; set; }
        public string Entity { get; set; }
        public string SourceSystem { get; set; }
        public string SalesOrderNumber { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string Product { get; set; }
        public string Category { get; set; }
        public Nullable<int> OrderQuantity { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
    }
}
