//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwoCents.Azure.Edmx.Common
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntityModelCommon : DbContext
    {
        public EntityModelCommon()
            : base("name=EntityModelCommon")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Fault> Faults { get; set; }
        public virtual DbSet<ProcessDefinition> ProcessDefinitions { get; set; }
        public virtual DbSet<Process> Processes { get; set; }
        public virtual DbSet<ProcessFlow> ProcessFlows { get; set; }
        public virtual DbSet<ProcessFlowBU> ProcessFlowBUs { get; set; }
        public virtual DbSet<ProcessStep> ProcessSteps { get; set; }
    }
}
