//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwoCents.Azure.Edmx.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessFlowBU
    {
        public long SequenceId { get; set; }
        public string Entity { get; set; }
        public string EntityId { get; set; }
        public Nullable<long> ProcessId { get; set; }
        public Nullable<long> StepId { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Status { get; set; }
        public string Notification { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> IsLastStep { get; set; }
    }
}
