//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwoCents.Azure.Edmx.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessDefinition
    {
        public long ProcessId { get; set; }
        public long StepId { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Status { get; set; }
        public string Notification { get; set; }
        public Nullable<bool> IsLastStep { get; set; }
    
        public virtual Process Process { get; set; }
        public virtual ProcessStep ProcessStep { get; set; }
    }
}
