//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwoCents.Azure.Edmx.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessStep
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProcessStep()
        {
            this.ProcessDefinitions = new HashSet<ProcessDefinition>();
        }
    
        public long StepId { get; set; }
        public string Name { get; set; }
        public string Version { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcessDefinition> ProcessDefinitions { get; set; }
    }
}
